MvcStok/Controllers/MusterilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity; // LİB
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class MusterilerController : Controller
    {
        // GET: Musteriler
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p, int sayfa = 1)
        {
            //var degerler = db.TBL_MUSTERILER.ToList();
           // var degerler = db.TBL_MUSTERILER.ToList().ToPagedList(sayfa, 4);
            var degerler = from d in db.TBL_MUSTERILER select d; //arama paneli için
            if (!string.IsNullOrEmpty(p)) //eğer p boş değilse arama paneli çalışır.
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList().ToPagedList(sayfa,4));
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]

        //MÜŞTERİ EKLEME
        public ActionResult YeniMusteri(TBL_MUSTERILER p2)
        {

            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBL_MUSTERILER.Add(p2);
            db.SaveChanges();
            return View();

        }
        //MÜŞTERİ SİLME
        public ActionResult MusteriSil(int id)
        {
            var musteri = db.TBL_MUSTERILER.Find(id);
            db.TBL_MUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //SAYFALAR ARASI VERİ TAŞIMA
        public ActionResult MusteriGetir(int id)
        {
            var musterii = db.TBL_MUSTERILER.Find(id);
            return View("MusteriGetir", musterii);

        }

        //GÜNCELLEME
        public ActionResult MusteriGuncelle(TBL_MUSTERILER p1)
        {
            var mstri = db.TBL_MUSTERILER.Find(p1.MUSTERIID);
            mstri.MUSTERIAD = p1.MUSTERIAD;
            mstri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

MvcStok/Views/Musteriler/Index.cshtml
@using MvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBL_MUSTERILER>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteriler", FormMethod.Get))
{

    <p>
        <b>Aranacak Müşteri Adı: </b>  @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>


}
    <!--MÜŞTERİLER LİSTESİ-->

<table class="table table-bordered">

    <tr>
        <th>MÜŞTERİ ID</th>
        <th>MÜŞTERİ ADI</th>
        <th>MÜŞTERİ SOYADI</th>
        <th>MÜŞTERİ SİL</th>
        <th>MÜŞTERİ GÜNCELLE</th>
        <th>ALERT</th>

    </tr>

    <tbody>

        @foreach (var musteri in Model)
        {

            <tr>

                <th>@musteri.MUSTERIID</th>
                <td>@musteri.MUSTERIAD</td>
                <td>@musteri.MUSTERISOYAD</td>
                <td><a href="/Musteriler/MusteriSil/@musteri.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/Musteriler/MusteriGetir/@musteri.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                <!--Alert-->
                <td>@Html.ActionLink("SİL", "MusteriSil", new { id = musteri.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor musunuz?')" })</td>


            </tr>



        }

    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))

<a href="/Musteriler/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE </a>

MvcStok/Views/Musteriler/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBL_MUSTERILER


@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using(Html.BeginForm("MusteriGuncelle","Musteriler",FormMethod.Post))
{
    <div class="form-group">

        <!--LİNQ Kullanımı-->
        @Html.LabelFor(m=>m.MUSTERIID)
        @Html.TextBoxFor(m=>m.MUSTERIID, new { @class="form-control"})
        <br/>   

        @Html.LabelFor(m=>m.MUSTERIAD)
        @Html.TextBoxFor(m=>m.MUSTERIAD, new { @class="form-control"})

        <br/>

        @Html.LabelFor(m=>m.MUSTERISOYAD)
        @Html.TextBoxFor(m=>m.MUSTERISOYAD, new { @class="form-control"})
    </div>


    
     <div style="margin-top:15px">

    <button class="btn btn-warning">MÜŞTERİ GÜNCELLE</button>
     </div>

 


}

MvcStok/Views/Musteriler/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBL_MUSTERILER


@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



<!-- Form elemanları kullanıcı bilgi girişinde kullanılır.-->

    <form class="form-group" method="post">
        <!--form butona tıkladıgımda işleyecek ve post işlemi işleyecek post önemli-->
        @*<div>
            <label>Müşteri Adı</label>
            <input type="text" class="form-control" name="MUSTERIAD" />   name databasedeki isimle aynı olmalı.
        </div>*@

        <div>
            <label>Müşteri Adı</label>
            @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:red" })
        </div>

        <div>
            <label>Müşteri Soyadı</label>
            <input type="text" class="form-control" name="MUSTERISOYAD"/>   @*name databasedeki isimle aynı olmalı.*@
        </div>

   


        <div style="margin-top:15px">
            <button class="btn btn-info" id="btn1">Müşteri Ekle</button>
        </div>

        <!--ALERT İŞLEMİ-->
        <script>
            $('#btn1').click(function () {

                alert('Müşteri Ekleme İşlemi Yapıldı.');
            });
            
        </script>

    </form>