MvcStok/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity; //mvcstok projesi içinde models klasörü içinde bulunan entity klasörünü çağırdık.
using PagedList;
using PagedList.Mvc;



namespace MvcStok.Controllers
{
    public class UrunlerController : Controller
    {
        // GET: Urunler

        MvcDbStokEntities db = new MvcDbStokEntities();

        public ActionResult Index(int sayfa = 1)
        {
            //var degerler = db.TBL_URUNLER.ToList();
            var degerler = db.TBL_URUNLER.ToList().ToPagedList(sayfa, 5);
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniUrun()
        {
            //DROPDOWNLİST , LİNQ kullanımı
            //tblkategorilerin listesini çek i değişkenine ata.
            List<SelectListItem> degerler = (from i in db.TBL_KATEGORILER.ToList()
                                             select new SelectListItem
                                             {

                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()

                                             }).ToList();
            //ViewBag, Controller'da oluşturulan bir yapıyı View kısmına taşımak için kullanılır. 
            ViewBag.dgr = degerler;  //controller tarafındaki ifadeyi diğer sayfaya taşır.
            return View();
        }
        [HttpPost]

        public ActionResult YeniUrun(TBL_URUNLER p3)
        {
            //firstordefault :linq içinde bulunur.Liste içerisinde seçtiğimiz ilk değeri getirir
            //amaç burada KATEGORIID yi almak.
            var ktg = db.TBL_KATEGORILER.Where(m => m.KATEGORIID == p3.TBL_KATEGORILER.KATEGORIID).FirstOrDefault();
            p3.TBL_KATEGORILER = ktg;

            db.TBL_URUNLER.Add(p3);
            db.SaveChanges();
            //  return View();
            return RedirectToAction("Index"); //kaydetme işlemi gerçekleştikten sonra bizi index sayfasına geri yönlendirir.
        }

        public ActionResult UrunSil(int id)
        {
            var urunler = db.TBL_URUNLER.Find(id);
            db.TBL_URUNLER.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //SAYFALAR ARASI VERİ TAŞIMA
        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBL_URUNLER.Find(id);
            List<SelectListItem> degerler = (from i in db.TBL_KATEGORILER.ToList()
                                             select new SelectListItem
                                             {

                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;

            return View("UrunGetir", urun);
        }

        //GÜNCELLE
        public ActionResult UrunGuncelle(TBL_URUNLER p1)
        {

            var urn = db.TBL_URUNLER.Find(p1.URUNID);
            urn.URUNAD = p1.URUNAD;
            urn.MARKA = p1.MARKA;
            // urn.URUNKATEGORI = p1.URUNKATEGORI;
            var ktg = db.TBL_KATEGORILER.Where(m => m.KATEGORIID == p1.TBL_KATEGORILER.KATEGORIID).FirstOrDefault();
            urn.URUNKATEGORI = ktg.KATEGORIID;
            urn.FIYAT = p1.FIYAT;
            urn.STOK = p1.STOK;

            db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

MvcStok/Views/Urunler/Index.cshtml
@using MvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBL_URUNLER>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!-- ÜRÜNLER LİSTELEME-->

<table id="tbl1" class="table table-bordered">
    <thead>
        <!-- thead tablonun konu başlığının etiketi-->
        <tr>
            <th>ÜRÜN ID</th>
            <th>ÜRÜN ADI</th>
            <th>ÜRÜN MARKASI</th>
            <th>ÜRÜN KATEGORİ</th>
            <th>ÜRÜN FİYATI</th>
            <th>STOK</th>
            <th>ÜRÜN SİL</th>
            <th>ÜRÜN GÜNCELLE</th>
            <th>ALERT</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urnlr in Model)
        {
        <tr>
            <th>@urnlr.URUNID</th>
            <td>@urnlr.URUNAD</td>
            <td>@urnlr.MARKA</td>
            <td>@urnlr.TBL_KATEGORILER.KATEGORIAD</td>   <!--İNNER JOİN KARŞILIĞI-->
            <td>@urnlr.FIYAT</td>
            <td>@urnlr.STOK</td>
            <td><a href="/Urunler/UrunSil/@urnlr.URUNID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Urunler/UrunGetir/@urnlr.URUNID" class="btn btn-success">GÜNCELLE</a></td>
<!--Alert--> <td>@Html.ActionLink("SİL", "UrunSil", new { id = urnlr.URUNID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor musunuz?')" })</td>
        </tr>
        }

    </tbody>
</table>
<!--paging işlemi-->
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))

<a href="/Urunler/YeniUrun/" class="btn btn-primary">YENİ ÜRÜN EKLE</a> 

<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-html5-1.5.6/fh-3.1.4/datatables.min.js"></script>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

<script>
    $('#tbl1').DataTable();

    
</script>

MvcStok/Views/Urunler/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBL_URUNLER

@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("UrunGuncelle", "Urunler", FormMethod.Post))
{




    <div class="form-group">

        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m => m.TBL_KATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })

        @*@Html.LabelFor(m => m.TBL_KATEGORILER.KATEGORIAD)*@
        @*@Html.TextBoxFor(m => m.TBL_KATEGORILER.KATEGORIAD, new { @class = "form-control" })*@

        <br />
        @Html.LabelFor(m => m.FIYAT)
        @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })

    </div>  

<div style="margin-top:15px">
    <button class="btn btn-warning">Ürün Güncelle</button>
</div>

}

MvcStok/Views/Urunler/YeniUrun.cshtml
@model MvcStok.Models.Entity.TBL_URUNLER


@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


    <form class="form-group" method="post">

        <div>
            <label>Ürün Adı</label>
            <input type="text" class="form-control" name="URUNAD" required="" maxlength="50"/>
        </div>

        <div>
            <label>Ürün Markası</label>
            <input type="text" class="form-control" name="MARKA" placeholder="Markayı Giriniz:"  required="" /> 
        </div>

        <div>

            <label>Ürün Kategorisi Seçiniz</label>
          <!-- <input type="text" class="form-control" name="URUNKATEGORI" />  -->

            <!-- m modelden geliyor , aşagıda linq kullanımı var.-->
          @Html.DropDownListFor(m => m.TBL_KATEGORILER.KATEGORIID , (List<SelectListItem>)ViewBag.dgr, new { @class="form-control"})
            <!--KATEGORIID bizim ekleme yapacak oldugumuz alan.-->
        </div>

        <div>
            <label>Ürün Fiyat</label>
            <input type="text" class="form-control" name="FIYAT"  required=""/>

        </div>

        <div>

            <label>Ürün Stok</label>
            <input type="text" class="form-control" name="STOK"  required=""/>
        </div>

        <div style="margin-top:15px">
            <button class="btn btn-info" id="btn1">Ürün Ekle</button>
        </div>

        <script>

            $('#btn1').click(function () {

                alert("Ürün Ekleme İşlemi Yapıldı.");
            });

        </script>



    </form>